export const Currencies = [
  { value: "AFN", label: "🇦🇫 Afghan Afghani", locale: "ps-AF" },
  { value: "ALL", label: "🇦🇱 Albanian Lek", locale: "sq-AL" },
  { value: "AOA", label: "🇦🇴 Angolan Kwanza", locale: "pt-AO" },
  { value: "ARS", label: "🇦🇷 Argentine Peso", locale: "es-AR" },
  { value: "AMD", label: "🇦🇲 Armenian Dram", locale: "hy-AM" },
  { value: "AWG", label: "🇦🇼 Aruban Florin", locale: "nl-AW" },
  { value: "AUD", label: "🇦🇺 Australian Dollar", locale: "en-AU" },
  { value: "AZN", label: "🇦🇿 Azerbaijani Manat", locale: "az-AZ" },
  { value: "BSD", label: "🇧🇸 Bahamian Dollar", locale: "en-BS" },
  { value: "BHD", label: "🇧🇭 Bahraini Dinar", locale: "ar-BH" },
  { value: "BDT", label: "🇧🇩 Bangladeshi Taka", locale: "bn-BD" },
  { value: "BBD", label: "🇧🇧 Barbadian Dollar", locale: "en-BB" },
  { value: "BYN", label: "🇧🇾 Belarusian Ruble", locale: "be-BY" },
  { value: "BZD", label: "🇧🇿 Belize Dollar", locale: "en-BZ" },
  { value: "BMD", label: "🇧🇲 Bermudian Dollar", locale: "en-BM" },
  { value: "BTN", label: "🇧🇹 Bhutanese Ngultrum", locale: "dz-BT" },
  { value: "BOB", label: "🇧🇴 Bolivian Boliviano", locale: "es-BO" },
  { value: "BWP", label: "🇧🇼 Botswana Pula", locale: "en-BW" },
  { value: "BRL", label: "🇧🇷 Brazilian Real", locale: "pt-BR" },
  { value: "GBP", label: "🇬🇧 British Pound", locale: "en-GB" },
  { value: "BND", label: "🇧🇳 Brunei Dollar", locale: "ms-BN" },
  { value: "BGN", label: "🇧🇬 Bulgarian Lev", locale: "bg-BG" },
  { value: "BIF", label: "🇧🇮 Burundian Franc", locale: "fr-BI" },
  { value: "MMK", label: "🇲🇲 Burmese Kyat", locale: "my-MM" },
  { value: "KHR", label: "🇰🇭 Cambodian Riel", locale: "km-KH" },
  { value: "CAD", label: "🇨🇦 Canadian Dollar", locale: "en-CA" },
  { value: "CVE", label: "🇨🇻 Cape Verdean Escudo", locale: "pt-CV" },
  { value: "KYD", label: "🇰🇾 Cayman Dollar", locale: "en-KY" },
  { value: "XAF", label: "🇨🇲 Central African CFA", locale: "fr-CM" },
  { value: "XPF", label: "🇵🇫 CFP Franc", locale: "fr-PF" },
  { value: "CLP", label: "🇨🇱 Chilean Peso", locale: "es-CL" },
  { value: "CNY", label: "🇨🇳 Chinese Yuan", locale: "zh-CN" },
  { value: "COP", label: "🇨🇴 Colombian Peso", locale: "es-CO" },
  { value: "KMF", label: "🇰🇲 Comorian Franc", locale: "ar-KM" },
  { value: "CDF", label: "🇨🇩 Congolese Franc", locale: "fr-CD" },
  { value: "CRC", label: "🇨🇷 Costa Rican Colón", locale: "es-CR" },
  { value: "HRK", label: "🇭🇷 Croatian Kuna", locale: "hr-HR" },
  { value: "CUP", label: "🇨🇺 Cuban Peso", locale: "es-CU" },
  { value: "CUC", label: "🇨🇺 Cuban Convertible Peso", locale: "es-CU" },
  { value: "CZK", label: "🇨🇿 Czech Koruna", locale: "cs-CZ" },
  { value: "DKK", label: "🇩🇰 Danish Krone", locale: "da-DK" },
  { value: "DJF", label: "🇩🇯 Djiboutian Franc", locale: "fr-DJ" },
  { value: "DOP", label: "🇩🇴 Dominican Peso", locale: "es-DO" },
  { value: "EGP", label: "🇪🇬 Egyptian Pound", locale: "ar-EG" },
  { value: "ERN", label: "🇪🇷 Eritrean Nakfa", locale: "ti-ER" },
  { value: "ETB", label: "🇪🇹 Ethiopian Birr", locale: "am-ET" },
  { value: "EUR", label: "🇪🇺 Euro", locale: "de-DE" },
  { value: "FKP", label: "🇫🇰 Falkland Pound", locale: "en-FK" },
  { value: "FJD", label: "🇫🇯 Fijian Dollar", locale: "en-FJ" },
  { value: "GMD", label: "🇬🇲 Gambian Dalasi", locale: "en-GM" },
  { value: "GEL", label: "🇬🇪 Georgian Lari", locale: "ka-GE" },
  { value: "GHS", label: "🇬🇭 Ghanaian Cedi", locale: "en-GH" },
  { value: "GIP", label: "🇬🇮 Gibraltar Pound", locale: "en-GI" },
  { value: "GTQ", label: "🇬🇹 Guatemalan Quetzal", locale: "es-GT" },
  { value: "GNF", label: "🇬🇳 Guinean Franc", locale: "fr-GN" },
  { value: "GYD", label: "🇬🇾 Guyanese Dollar", locale: "en-GY" },
  { value: "HTG", label: "🇭🇹 Haitian Gourde", locale: "ht-HT" },
  { value: "HNL", label: "🇭🇳 Honduran Lempira", locale: "es-HN" },
  { value: "HKD", label: "🇭🇰 Hong Kong Dollar", locale: "zh-HK" },
  { value: "HUF", label: "🇭🇺 Hungarian Forint", locale: "hu-HU" },
  { value: "ISK", label: "🇮🇸 Icelandic Króna", locale: "is-IS" },
  { value: "INR", label: "🇮🇳 Indian Rupee", locale: "en-IN" },
  { value: "IDR", label: "🇮🇩 Indonesian Rupiah", locale: "id-ID" },
  { value: "IRR", label: "🇮🇷 Iranian Rial", locale: "fa-IR" },
  { value: "IQD", label: "🇮🇶 Iraqi Dinar", locale: "ar-IQ" },
  { value: "JMD", label: "🇯🇲 Jamaican Dollar", locale: "en-JM" },
  { value: "JPY", label: "🇯🇵 Japanese Yen", locale: "ja-JP" },
  { value: "JOD", label: "🇯🇴 Jordanian Dinar", locale: "ar-JO" },
  { value: "KZT", label: "🇰🇿 Kazakhstani Tenge", locale: "kk-KZ" },
  { value: "KES", label: "🇰🇪 Kenyan Shilling", locale: "sw-KE" },
  { value: "KWD", label: "🇰🇼 Kuwaiti Dinar", locale: "ar-KW" },
  { value: "KGS", label: "🇰🇬 Kyrgyzstani Som", locale: "ky-KG" },
  { value: "LAK", label: "🇱🇦 Lao Kip", locale: "lo-LA" },
  { value: "LBP", label: "🇱🇧 Lebanese Pound", locale: "ar-LB" },
  { value: "LSL", label: "🇱🇸 Lesotho Loti", locale: "st-LS" },
  { value: "LRD", label: "🇱🇷 Liberian Dollar", locale: "en-LR" },
  { value: "MOP", label: "🇲🇴 Macanese Pataca", locale: "zh-MO" },
  { value: "MKD", label: "🇲🇰 Macedonian Denar", locale: "mk-MK" },
  { value: "MGA", label: "🇲🇬 Malagasy Ariary", locale: "mg-MG" },
  { value: "MWK", label: "🇲🇼 Malawian Kwacha", locale: "ny-MW" },
  { value: "MYR", label: "🇲🇾 Malaysian Ringgit", locale: "ms-MY" },
  { value: "MVR", label: "🇲🇻 Maldivian Rufiyaa", locale: "dv-MV" },
  { value: "MRO", label: "🇲🇷 Mauritanian Ouguiya", locale: "ar-MR" },
  { value: "MUR", label: "🇲🇺 Mauritian Rupee", locale: "en-MU" },
  { value: "MXN", label: "🇲🇽 Mexican Peso", locale: "es-MX" },
  { value: "MDL", label: "🇲🇩 Moldovan Leu", locale: "ro-MD" },
  { value: "MNT", label: "🇲🇳 Mongolian Tögrög", locale: "mn-MN" },
  { value: "MAD", label: "🇲🇦 Moroccan Dirham", locale: "ar-MA" },
  { value: "MZN", label: "🇲🇿 Mozambican Metical", locale: "pt-MZ" },
  { value: "NAD", label: "🇳🇦 Namibian Dollar", locale: "en-NA" },
  { value: "NPR", label: "🇳🇵 Nepalese Rupee", locale: "ne-NP" },
  { value: "ANG", label: "🇨🇼 Netherlands Antillean Guilder", locale: "nl-CW" },
  { value: "NZD", label: "🇳🇿 New Zealand Dollar", locale: "en-NZ" },
  { value: "NIO", label: "🇳🇮 Nicaraguan Córdoba", locale: "es-NI" },
  { value: "NGN", label: "🇳🇬 Nigerian Naira", locale: "en-NG" },
  { value: "KPW", label: "🇰🇵 North Korean Won", locale: "ko-KP" },
  { value: "NOK", label: "🇳🇴 Norwegian Krone", locale: "nb-NO" },
  { value: "OMR", label: "🇴🇲 Omani Rial", locale: "ar-OM" },
  { value: "PKR", label: "🇵🇰 Pakistani Rupee", locale: "en-PK" },
  { value: "PAB", label: "🇵🇦 Panamanian Balboa", locale: "es-PA" },
  { value: "PGK", label: "🇵🇬 Papua New Guinean Kina", locale: "en-PG" },
  { value: "PYG", label: "🇵🇾 Paraguayan Guaraní", locale: "es-PY" },
  { value: "PEN", label: "🇵🇪 Peruvian Sol", locale: "es-PE" },
  { value: "PHP", label: "🇵🇭 Philippine Peso", locale: "en-PH" },
  { value: "PLN", label: "🇵🇱 Polish Złoty", locale: "pl-PL" },
  { value: "QAR", label: "🇶🇦 Qatari Riyal", locale: "ar-QA" },
  { value: "RON", label: "🇷🇴 Romanian Leu", locale: "ro-RO" },
  { value: "RUB", label: "🇷🇺 Russian Ruble", locale: "ru-RU" },
  { value: "RWF", label: "🇷🇼 Rwandan Franc", locale: "rw-RW" },
  { value: "SHP", label: "🇸🇭 St. Helena Pound", locale: "en-SH" },
  { value: "SVC", label: "🇸🇻 Salvadoran Colón", locale: "es-SV" },
  { value: "WST", label: "🇼🇸 Samoan Tala", locale: "sm-WS" },
  { value: "STN", label: "🇸🇹 São Tomé Dobra", locale: "pt-ST" },
  { value: "SAR", label: "🇸🇦 Saudi Riyal", locale: "ar-SA" },
  { value: "RSD", label: "🇷🇸 Serbian Dinar", locale: "sr-RS" },
  { value: "SCR", label: "🇸🇨 Seychellois Rupee", locale: "en-SC" },
  { value: "SLL", label: "🇸🇱 Sierra Leonean Leone", locale: "en-SL" },
  { value: "SGD", label: "🇸🇬 Singapore Dollar", locale: "en-SG" },
  { value: "SBD", label: "🇸🇧 Solomon Dollar", locale: "en-SB" },
  { value: "SOS", label: "🇸🇴 Somali Shilling", locale: "so-SO" },
  { value: "ZAR", label: "🇿🇦 South African Rand", locale: "en-ZA" },
  { value: "SSP", label: "🇸🇸 South Sudanese Pound", locale: "en-SS" },
  { value: "KRW", label: "🇰🇷 South Korean Won", locale: "ko-KR" },
  { value: "LKR", label: "🇱🇰 Sri Lankan Rupee", locale: "si-LK" },
  { value: "SDG", label: "🇸🇩 Sudanese Pound", locale: "ar-SD" },
  { value: "SRD", label: "🇸🇷 Surinamese Dollar", locale: "nl-SR" },
  { value: "SZL", label: "🇸🇿 Swazi Lilangeni", locale: "en-SZ" },
  { value: "SEK", label: "🇸🇪 Swedish Krona", locale: "sv-SE" },
  { value: "CHF", label: "🇨🇭 Swiss Franc", locale: "de-CH" },
  { value: "SYP", label: "🇸🇾 Syrian Pound", locale: "ar-SY" },
  { value: "TWD", label: "🇹🇼 New Taiwan Dollar", locale: "zh-TW" },
  { value: "TJS", label: "🇹🇯 Tajikistani Somoni", locale: "tg-TJ" },
  { value: "TZS", label: "🇹🇿 Tanzanian Shilling", locale: "sw-TZ" },
  { value: "THB", label: "🇹🇭 Thai Baht", locale: "th-TH" },
  { value: "TOP", label: "🇹🇴 Tongan Paʻanga", locale: "to-TO" },
  { value: "TTD", label: "🇹🇹 Trinidad & Tobago Dollar", locale: "en-TT" },
  { value: "TRY", label: "🇹🇷 Turkish Lira", locale: "tr-TR" },
  { value: "TMT", label: "🇹🇲 Turkmenistani Manat", locale: "tk-TM" },
  { value: "AED", label: "🇦🇪 UAE Dirham", locale: "ar-AE" },
  { value: "UGX", label: "🇺🇬 Ugandan Shilling", locale: "sw-UG" },
  { value: "UAH", label: "🇺🇦 Ukrainian Hryvnia", locale: "uk-UA" },
  { value: "USD", label: "🇺🇸 United States Dollar", locale: "en-US" },
  { value: "UYU", label: "🇺🇾 Uruguayan Peso", locale: "es-UY" },
  { value: "UZS", label: "🇺🇿 Uzbekistani Som", locale: "uz-UZ" },
  { value: "VUV", label: "🇻🇺 Vanuatu Vatu", locale: "bi-VU" },
  { value: "VED", label: "🇻🇪 Venezuelan Bolívar", locale: "es-VE" },
  { value: "VND", label: "🇻🇳 Vietnamese Dong", locale: "vi-VN" },
  { value: "XOF", label: "🇨🇫 West African CFA", locale: "fr-CF" },
  { value: "YER", label: "🇾🇪 Yemeni Rial", locale: "ar-YE" },
  { value: "ZMW", label: "🇿🇲 Zambian Kwacha", locale: "en-ZM" },
  { value: "ZWL", label: "🇿🇼 Zimbabwean Dollar", locale: "en-ZW" },
];

export type Currency = (typeof Currencies)[0];
